### ISSUE TITLE
Log line formatting proposal

### ISSUE THREAD

**Issue by xoebus** [cloudfoundry/lager#32]
This is a proposal for a new log line format that is easier for humans to read while still allowing deterministic machine parsing. It is inspired heavily by the [glog](https://github.com/golang/glog) log line format.

Both these log lines represent the same event:

**Current**
```
{"timestamp":"1521035101.769078493","source":"perm-monitor","message":"perm-monitor.query-probe.run.has-assigned-permission.failed-to-find-permissions","log_level":2,"data":{"actor.id":"query-probe","actor.issuer":"system","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","session":"2.8089732.1"}}
```

**Proposed**
```
E0316 00:06:52.769078493 perm-monitor[4124] 2.8089732.1 perm-monitor.query-probe.run.has-assigned-permission.failed-to-find-permissions {"actor.id":"query-probe","actor.issuer":"system","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
```

This line contains, in order:

* Error/Debug/Info
* Date
* Time
* Component Name
* PID
* Session
* Message
* Data

It is shorter than the old format.

The notable differences between the old and the new format are:

* Log levels are represented as letters rather than slightly magical numbers. In order to keep the information density high this is a single letter. It's at the start of the line so that you can `grep` for all the errors in a log file by searching for letters at the start of the line. This wouldn't be possible elsewhere in the line due to occurrences of `D`, `I`, and `E` will be common in the rest of line.

* The year is removed from the date because it's rare that logs are useful for over 365 days.

* The time and date are in a lexicographical  order such that you could combine two log files together with `sort -k 1`.

* The PID is included because it is a short, useful identifier which can be used to distinguish between multiple worker processes and can be used to see if a process restarted.

* Only `data` is left in the JSON because it contains "untrusted" input. This means that this format will have similar performance to the existing logger. If we want to radically improve the performance then we need to remove the JSON completely and restructure the `Data` data structure to eliminate allocations and copying.

What do you think?

**Comment by vito** [comment]
`E0316` kind of looks like an error code to me. I had no idea what it was until I read that the numbers indicate a date.

Hmm, to be honest I'm not sure showing a date and time is even necessary. I kind of like how [Logrus](https://github.com/sirupsen/logrus) instead shows "seconds since start" which more easily gives you an idea of the timing between log lines. I think if you care about precise dates/times you're probably already using `rsyslog` and/or a log sink like PaperTrail which tracks that for you and lets you do fancy temporal filters.

For the `data`, could we show it as something like `a=b c=d e="f !special chars"`? Curlies and quotes are annoying to deal with since some regex engines escape them, some don't, and they're special characters in the shell. We can probably trust the key to not contain untrusted stuff, but we can just JSON encode either if they contain funny characters (or spaces). Grepping for `user=vito` or or `build=1` something would be nicer to type than `'"user": ?"vito"` (because who can remember whether there's a space after the `:` or not).

**Comment by xoebus** [comment]
> E0316 kind of looks like an error code to me. I had no idea what it was until I read that the numbers indicate a date.

Yeah, that got me too. For what it's worth, that format is taken from glog.

> Hmm, to be honest I'm not sure showing a date and time is even necessary. I kind of like how Logrus instead shows "seconds since start" which more easily gives you an idea of the timing between log lines. I think if you care about precise dates/times you're probably already using rsyslog and/or a log sink like PaperTrail which tracks that for you and lets you do fancy temporal filters.

One of the things I like about Zap is that it has a development and production mode. What if we added the colors and timestamps in development mode and removed the timestamps (or altered their format to be time since start) in production logs? That way you wouldn't get the duplication of the timestamps when viewing them in syslog.

> For the data, could we show it as something like a=b c=d e="f !special chars"? Curlies and quotes are annoying to deal with since some regex engines escape them, some don't, and they're special characters in the shell. We can probably trust the key to not contain untrusted stuff, but we can just JSON encode either if they contain funny characters (or spaces). Grepping for user=vito or or build=1 something would be nicer to type than '"user": ?"vito" (because who can remember whether there's a space after the : or not).

In principle, I much prefer the format you propose. Unfortunately, based on the performance experiments I did, the time to emit a log line nearly doubles if you scan it to see if there are unprintable characters and escape them.

I think there are two things we could do:

- Separate the data elements with tabs and put the onus on the developer to avoid logging a tab or newline. I think these characters should be rare enough that this is reasonable.

- Ask the developer to escape the strings when they declare them so we don't need to do the work each time we emit a log line.

e.g.

```go
logger.Error("failed-to-flail", err, lager.String("key", "bad++\n\tvalue"), lager.Int("count", 5))
```

I've got some ideas for some performance improvements using **_DaTa StRuCtUrEs_** if we can turn data into a list rather than a map.

**Comment by vito** [comment]
> One of the things I like about Zap is that it has a development and production mode. What if we added the colors and timestamps in development mode and removed the timestamps (or altered their format to be time since start) in production logs? That way you wouldn't get the duplication of the timestamps when viewing them in syslog.

Maybe they should just be toggled via flags? Development vs production is a bit opinionated terminology since someone may want to omit the timestamps in production because their logs are going to something that does timestamps for them (like rsyslog or systemd's log stack, etc).

Come to think of it, I think those systems also have structures in place for the component and pid, so in many cases those could be redundant. In the interest of maximum prettiness it may be worth considering omitting those, too (or more flags). The current Lager format already doesn't include the pid and it doesn't seem like anyone's complained. Showing the component is also fairly redundant since everyone has it at the start of their messages anyway. (Which is kind of weird! Lager has a notion of a component/system but to construct a Logger you have to give it a string, which ends up at the start of every. single. message. anyway. Maybe we should fix that in v2?)

> In principle, I much prefer the format you propose. Unfortunately, based on the performance experiments I did, the time to emit a log line nearly doubles if you scan it to see if there are unprintable characters and escape them.

Fair. I guess I'm not sure what the target user is for this new format. For Concourse's use case in https://github.com/concourse/bin/issues/38 I don't really care about performance that much since it'll almost never be the bottleneck, but if we're considering this as a new default format for Lager I could see why performance would be a concern.

---

All things considered, I guess I'm saying Logrus' log format is pretty much ideal, lol. I was gonna mock one up but it turned out to just be exactly what theirs is.

**Comment by emalm** [comment]
Closing this out due to inactivity. Sounds like we need some actual user feedback and research to make these ideas actionable.
