### ISSUE TITLE
Print the line number of message with lager

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/lager#34]
When use lager to do logging, it print out a json format message. There is no line number where the log message was triggered. Does lager support it? Or how can I do it with lager?

**Comment by jvshahid** [comment]
No, you can't print the `file:line` where the log was triggered that today. We (the diego team) usually have a message that is distinguishable enough, either by itself or because it has a session prefix to identify where it came from. I honestly haven't felt the need for file:line but I'm happy to hear your thoughts. First, I would recommend making use of [Session](https://godoc.org/code.cloudfoundry.org/lager#Logger) to nest sessions and add a prefix to the log message.

**Comment by qibobo** [comment]
@jvshahid Sounds reasonable. Thank you.
